### ISSUE TITLE
missing swivel and tracking issues

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1771]
Several minor things need to be addressed:
- [x] Unguided launchers don't have swivel (hard to hit)
- [x] Forward beams don't have swivel (hard to hit)
- [x] Beams don't have any tracking and by extension they don't have any heat

**Comment by bobbens** [comment]
Unguided launchers now have swivel.

**Comment by bobbens** [comment]
Beams now have swivel.

**Comment by bobbens** [comment]
Beams heat up and fire slower.
